# Generated by Django 3.2.3 on 2021-05-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
